collections:
  columns
    order: 
      - columns/inequality and inefficiency.md

# port: 4000
# markdown:  kramdown
permalink: /:title
plugins: [ jekyll-feed, jekyll-seo-tag ]


title :       "Abr.Da.Great's Commonplace"
description : "Powered by Jekyll and Netlify"
author :      "Abr Bas"
url :         https://abrdgr8.netlify.app/


feed:
  path: /blog/feed.atom