#------------------------------- 
# General Site Settings

menu:
- {name: 'Blogs', url: ''}
- {name: 'Columns',     url: 'columns'}
- {name: 'Work',    url: 'work'}
- {name: 'Projects',    url: 'projects'}
- {name: 'Journal',    url: 'journal'}
- {name: 'Podcasts',  url: 'podcasts'}

#-------------------------------
# Work Section

work:
- {name: 'Copywriting 101',   url: 'work/copywriting'}
- {name: 'Content Writing',   url: 'work/content-writing'}
- {name: 'Column Writing',   url: 'work/column-writing'}
- {name: 'Songwriting', url: ' work/songwriting'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter',   link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'github',    link: 'https://github.com/lenpaul'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/lenpaul'}
- {icon: 'envelope',  link: 'mailto:mailto:l.nguyen.paul@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal Website for Portfolio Purposes'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section
# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: ''
